apiVersion: v1
kind: Service
metadata:
  name: {{ include "logos.fullname" . }}
  labels:
    app: {{ include "logos.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "logos.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
